# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YolJyw9VcF47on1Y197sFL1jJ5pgCbHu
"""

''' Python program to print all odd numbers in a list'''
list1 = [3,7,9,12,16,22,18,19]
for num in list1:
    if num % 2 != 0:
       print(num)

'''Python pogram to reverse a list in two ways'''
list  = [10,20,30,40,50]
list.reverse()
print(list)

'''Python program to find the sum of list element'''
list = [2,3,5,7,9]
sum = 0
for i in list:
  sum = sum+ i
  print(sum)

'''Python program to sort characters in descending order'''
sorting_char = ['a' , 'z' , 'k' , 'y' , 'i']
sorting_char.sort(reverse=True)
print(sorting_char)

'''Python program to find top two max numbers in a list'''
List = [100,10,50,108,121,7,55]

sorting = sorted(List) 

print("Max no:" , sorting[-1] )
print("Second Highest: " , sorting[-2] )

'''Write a program to find second highest number in an integer list'''
list1 = [4,67,23,77,98,101]
list1.sort()
 
print("Second largest element is:", list1[-2])

'''Python Program to check if a given character is a vowel or constant'''
checking_char = input("Enter any Character : ")
if checking_char in ('a', 'e', 'i', 'o', 'u'):
    print(checking_char," is a vowel.")
else:
    print(checking_char," is a consonant.")

list1 = []
for i in range (5):
     num=int(input("Enter an integer : "))
     list1.append(num)
list2 = []
for i in range (5):
     num=int(input("Enter an integer : "))
     list2.append(num)
print("List 1 : ",list1)
print("List 2: ",list2)

for i in list2 :
    list1.append(i)
print (" Merging List 1 and List 2 : " + str(list1))

'''Python Program to calculate factorial''' 
ip= int(input("Enter a number: "))
fact = 1

if ip < 0:
   print("Factorial does not exist for negative numbers")
elif ip == 0:
   print("The factorial of 0 is 1")
else:
   for i in range(1,ip + 1):
       fact=fact*i
   print("The factorial of",num,"=",fact)

'''Program to remove repeated characters from a string'''
string_ip = input("Enter Your Name : ")
string_list = []
for i in range(len(string_ip)):
    string_list.append(string_ip[i])
list2 = []
j = 0
for i in range(len(string_list)):
    if string_ip[i] not in list2:
        list2.insert(j, string_ip[i])
        j = j+1
print("Original Name : ", string_ip)
string_ip = ""
string_ip = string_ip.join(list2)
print("Removing repeated character : ", string_ip)